### ISSUE TITLE
How did you handle half-duplex constraint?

### ISSUE THREAD

**Issue by mnegroy** [signetlabdei/ns3-mmwave-iab#3]
Hi,

I read your paper "End-to-End Simulation of Integrated Access and Backhaul at mmWaves"
and have one question about the scheduling procedure.

Considering downlink traffic in simple 2 hop topology (Donor - IAB - UE),
the donor transmits PDCCH to the IAB node to schedule data transmission 2 subframes later.

My question is that how can the donor guarantee that the IAB node will receive the PDCCH?
Since the PDCCH is neither periodic nor pre-scheduled, the IAB node is maybe communicating with attached UE when the donor is transmitting the PDCCH.

Thanks.
Jungjun Kim

**Comment by mychele** [comment]
Hi!
Very good question.
For now we focus on the user plane and data channels. For the control, you can probably have some pre-configured slot structure in which the IAB node knows it should monitor the upstream PDCCH. However, at this stage, this is not implemented in the simulator.
Michele
