### ISSUE TITLE
still keep tracking？

### ISSUE THREAD

**Issue by kicejade** [signetlabdei/ns3-mmwave-iab#9]
Hi,

I am a student from Xiamen univeristy. I have read your paper "End-to-End Simulation of Integrated Access and Backhaul at mmWaves".
I noticed that you have said that you may keep track of the 3GPP specifications on this topic and may add new IAB features to the ns3-mmWave module at the end, but the repository is unmaintained. 
So I don't know if you still working on this topic. Do you have any progress about this topic you can share with us? 
Really appreciate it, thanks!

**Comment by pagmatt** [comment]
Hi!

We are indeed still working on the topic, and we are working on an updated IAB simulation module. We will release it in about 3/4 months, if everything goes according to plan.

Best,
Matteo

**Comment by kicejade** [comment]
Thanks a lot for your helpful feedback!
Wish you all the best in your plan!

Best，
Kice
